#!/usr/bin/python3
#
# make_examples.py
#

import xlsxwriter, datetime, decimal

# example01 with same integers
workbook = xlsxwriter.Workbook('examples/example01.xlsx')
workbook.set_properties({'created': datetime.datetime(2020,1,1,12,0,0)})
worksheet = workbook.add_worksheet()
worksheet.write(0,1,55)
worksheet.write(1,1,55)
worksheet.write(1,0,55)
workbook.close()

# example02 with multiple integers
workbook = xlsxwriter.Workbook('examples/example02.xlsx')
workbook.set_properties({'created': datetime.datetime(2020,1,1,12,0,0)})
worksheet = workbook.add_worksheet()
worksheet.write(0,1,55)
worksheet.write(0,2,66)
worksheet.write(0,3,77)
workbook.close()

# example02 with duplicate string
workbook = xlsxwriter.Workbook('examples/example03.xlsx')
workbook.set_properties({'created': datetime.datetime(2020,1,1,12,0,0)})
worksheet = workbook.add_worksheet()
worksheet.write(0,1,'Hello')
worksheet.write(0,2,'World')
worksheet.write(0,3,'Hello')
workbook.close()

# example04 with two worksheets
workbook = xlsxwriter.Workbook('examples/example04.xlsx')
workbook.set_properties({'created': datetime.datetime(2020,1,1,12,0,0)})
worksheet = workbook.add_worksheet()
worksheet.write(0,0,'Hello')
worksheet.write(0,1,'World')
worksheet.write(0,2,'Hello')
worksheet = workbook.add_worksheet()
worksheet.write(0,0,'Hallo')
worksheet.write(0,1,'World')
worksheet.write(0,2,'Hello')
workbook.close()

# example05 with named worksheet
workbook = xlsxwriter.Workbook('examples/example05.xlsx')
workbook.set_properties({'created': datetime.datetime(2020,1,1,12,0,0)})
worksheet = workbook.add_worksheet()
worksheet.write(0,0,'Hello')
worksheet.write(0,1,'World')
worksheet.write(0,2,'Hello')
worksheet = workbook.add_worksheet(name='MySheet')
worksheet.write(0,0,'Hallo')
worksheet.write(0,1,'World')
worksheet.write(0,2,'Hello')
worksheet = workbook.add_worksheet()
worksheet.write(0,0,'Hallo')
worksheet.write(0,1,'World')
worksheet.write(0,2,'Hello')
workbook.close()

# example06 = example05 plus date
workbook = xlsxwriter.Workbook('examples/example06.xlsx')
workbook.set_properties({'created': datetime.datetime(2020,1,1,12,0,0)})
date_format1 = workbook.add_format({'num_format': 'mmmm d yyyy'})
date_format2 = workbook.add_format({'num_format': 'mmm d yyyy'})
date_format3 = workbook.add_format({'num_format': 'mm dd yyyy'})
date_format4 = workbook.add_format({'num_format': 'yyyy-mm-dd'})
worksheet = workbook.add_worksheet()
worksheet.write(0,0,'Hello')
worksheet.write(0,1,'World')
worksheet.write(0,2,'Hello')
worksheet.write(0,3,datetime.datetime.strptime('2020-01-01', "%Y-%m-%d"), date_format1)
worksheet.write(1,3,datetime.datetime.strptime('2000-01-01', "%Y-%m-%d"), date_format2)
worksheet.write(2,3,datetime.datetime.strptime('1980-01-01', "%Y-%m-%d"), date_format3)
worksheet.write(2,4,datetime.datetime.strptime('1960-01-01', "%Y-%m-%d"), date_format4)
worksheet = workbook.add_worksheet(name='MySheet')
worksheet.write(0,0,'Hallo')
worksheet.write(0,1,'World')
worksheet.write(0,2,'Hello')
worksheet = workbook.add_worksheet()
worksheet.write(0,0,'Hallo')
worksheet.write(0,1,'World')
worksheet.write(0,2,'Hello')
workbook.close()

# example07 = example06 plus set row height
workbook = xlsxwriter.Workbook('examples/example07.xlsx')
workbook.set_properties({'created': datetime.datetime(2020,1,1,12,0,0)})
date_format = workbook.add_format({'num_format': 'mmmm d yyyy'})
worksheet = workbook.add_worksheet()
worksheet.set_row(0, 30)
worksheet.write(0,0,'Hello')
worksheet.write(0,1,'World')
worksheet.write(0,2,'Hello')
worksheet.write(0,3,datetime.datetime.strptime('2013-01-01', "%Y-%m-%d"), date_format)
worksheet = workbook.add_worksheet(name='MySheet')
worksheet.write(0,0,'Hallo')
worksheet.write(0,1,'World')
worksheet.write(0,2,'Hello')
worksheet = workbook.add_worksheet()
worksheet.write(0,0,'Hallo')
worksheet.write(0,1,'World')
worksheet.write(0,2,'Hello')
workbook.close()

# example08 = example07 plus two formulas
workbook = xlsxwriter.Workbook('examples/example08.xlsx')
workbook.set_properties({'created': datetime.datetime(2020,1,1,12,0,0)})
date_format = workbook.add_format({'num_format': 'mmmm d yyyy'})
worksheet = workbook.add_worksheet()
worksheet.set_row(0, 30)
worksheet.write(0,0,'Hello')
worksheet.write(0,1,'World')
worksheet.write(0,2,'Hello')
worksheet.write(0,3,datetime.datetime.strptime('2013-01-01', "%Y-%m-%d"), date_format)
worksheet = workbook.add_worksheet(name='MySheet')
worksheet.write(0,0,'Hallo')
worksheet.write(0,1,'World')
worksheet.write(0,2,'Hello')
worksheet = workbook.add_worksheet()
worksheet.write(0,0,'Hallo')
worksheet.write(0,1,'World')
worksheet.write(0,2,'Hello')
worksheet.write(0,3,100.50),
worksheet.write(1,3,100.50),
worksheet.write(2,3,100.50),
worksheet.write(3,3,100.50),
worksheet.write_formula(4,3,'=2+2')
worksheet.write_formula(5,3,'=SUM(D1:D4)')
workbook.close()

# example09 (merging cells)
workbook = xlsxwriter.Workbook('examples/example09.xlsx')
workbook.set_properties({'created': datetime.datetime(2020,1,1,12,0,0)})
worksheet = workbook.add_worksheet()
worksheet.set_row(0, 30)
worksheet.write('A1',11)
worksheet.write('B1',12)
worksheet.write('C1',13)
worksheet.write('D1',14)
worksheet.write('E1',15)
worksheet.write('A2',21)
worksheet.write('B2',22)
worksheet.write('C2',23)
worksheet.write('D2',24)
worksheet.write('E2',25)
worksheet.write('A3',31)
worksheet.write('B3',32)
worksheet.write('C3',33)
worksheet.write('D3',34)
worksheet.write('E3',35)
worksheet.write('A4',41)
worksheet.write('B4',42)
worksheet.write('C4',43)
worksheet.write('D4',44)
worksheet.write('E4',45)
worksheet.write('A5',51)
worksheet.write('B5',52)
worksheet.write('C5',53)
worksheet.write('D5',54)
worksheet.write('E5',55)
worksheet.write('A6',61)
worksheet.write('B6',62)
worksheet.write('C6',63)
worksheet.write('D6',64)
worksheet.write('E6',65)
worksheet.write('A7',71)
worksheet.write('B7',72)
worksheet.write('C7',73)
worksheet.write('D7',74)
worksheet.write('E7',75)
worksheet.write('A8',81)
worksheet.write('B8',82)
worksheet.write('C8',83)
worksheet.write('D8',84)
worksheet.write('E8',85)
worksheet.write('A9',91)
worksheet.write('B9',92)
worksheet.write('C9',93)
worksheet.write('D9',94)
worksheet.write('E9',95)
worksheet.merge_range('B2:D4', 'Merged Cells One') #, 'Merged Cells', merge_format)
worksheet.merge_range('B6:D8', 'Merged Cells Two') #, 'Merged Cells', merge_format)
worksheet.merge_range('B9:D9', 'Merged Cells Three') #, 'Merged Cells', merge_format)
workbook.close()

# example10
workbook = xlsxwriter.Workbook('examples/example10.xlsx')
workbook.set_properties({'created': datetime.datetime(2020,1,1,12,0,0)})
red_format = workbook.add_format({'bg_color': '#FF0000'})
green_format = workbook.add_format({'bg_color': 'green'})
bold_format = workbook.add_format({'bold': True})
bold_italic_format = workbook.add_format({'bold': True, 'italic': True})
fancy_format = workbook.add_format({'bg_color': 'green', 'bold': True, 'italic': True})
white_format = workbook.add_format({'bg_color': 'green', 'bold': True, 'italic': True, 'fg_color':'white'})
date_format = workbook.add_format({'num_format': 'mmmm d yyyy'})

worksheet = workbook.add_worksheet(name='Data Types')
worksheet.write(0,0,'String')
worksheet.write(0,1,'Example')
worksheet.write(1,0,'Integer')
worksheet.write(1,1,123)
worksheet.write(1,2,-123)
worksheet.write(2,0,'Float')
worksheet.write(2,1,123.456)
worksheet.write(2,2,-123.456)
worksheet.write(3,0,'Boolean')
worksheet.write(3,1,True)
worksheet.write(3,2,False)
worksheet.write(4,0,'None')
worksheet.write(4,1,None)
worksheet.write(5,0,'FixedPoint')
worksheet.write(5,1,decimal.Decimal(2)/3)
worksheet.write(5,2,-decimal.Decimal(2)/3)
worksheet.write(6,0,'Date')
worksheet.write(6,1,datetime.datetime.strptime('2013-01-13', "%Y-%m-%d"))
worksheet.write_datetime(6,1,datetime.datetime.strptime('2013-01-13', "%Y-%m-%d"))
worksheet.write(6,2,datetime.datetime.strptime('2013-01-13', "%Y-%m-%d"), date_format)
worksheet.write(7,2,datetime.datetime.strptime('2000-01-01', "%Y-%m-%d"), date_format)
worksheet.write(8,2,datetime.datetime.strptime('1990-01-01', "%Y-%m-%d"), date_format)
worksheet.write(9,2,datetime.datetime.strptime('1980-01-01', "%Y-%m-%d"), date_format)
worksheet.write(10,2,datetime.datetime.strptime('1970-01-01', "%Y-%m-%d"), date_format)
worksheet = workbook.add_worksheet(name='MySheet')
worksheet.set_row(2, 24)
worksheet.write(0,0,'Hallo', green_format)
worksheet.write(0,1,'World')
worksheet.write(0,2,'Hello')
worksheet = workbook.add_worksheet('Many Formats')
worksheet.write(0,0,'Red format', red_format)
worksheet.write(0,1,'Green format', green_format)
worksheet.write(0,2,'Bold format', bold_format)
worksheet.write(0,3,'Bold italic format', bold_italic_format)
worksheet.write(0,4,'Fancy format', fancy_format)
worksheet.write(0,5,'White format', white_format)
workbook.close()

# example11 unusual strings
workbook = xlsxwriter.Workbook('examples/example11.xlsx',{"strings_to_blanks": True})
workbook.set_properties({'created': datetime.datetime(2020,1,1,12,0,0)})
worksheet = workbook.add_worksheet()
worksheet.write(0,0,'Hello')
worksheet.write(1,0,' ')
worksheet.write(2,0,'   ')
worksheet.write(3,0,'')          # empty string
worksheet.write(4,0,'World')
worksheet.write(5,0,'trailing   ')
worksheet.write(6,0,'    leading')
worksheet.write(7,0,'    both spaces   ')
worksheet.write(8,0,'\t\t\tboth tabs\t\t\t')
workbook.close()

# example12 label and merged cells in one line
workbook = xlsxwriter.Workbook('examples/example12.xlsx')
workbook.set_properties({'created': datetime.datetime(2020,1,1,12,0,0)})
worksheet = workbook.add_worksheet()
worksheet.set_column(0,0,15)
worksheet.set_row(0,30)
label_format = workbook.add_format({'bg_color':'#C0A080', 'bold':False, 'font_size':20, 'valign':'vcenter', 'align':'center'})
worksheet.write(0,0,'LABEL', label_format)

merge_format = workbook.add_format({'italic':True, 'bold':False, 'font_size':20, 'valign':'vcenter'})
worksheet.merge_range('B1:H1', 'My New report', merge_format)

worksheet.write(2,0,'My')
worksheet.write(3,0,'Data')
worksheet.write(4,0,'comes')
worksheet.write(5,0,'here.')
workbook.close()

# example13 numeric spreadsheet with autofilter
workbook = xlsxwriter.Workbook('examples/example13.xlsx')
workbook.set_properties({'created': datetime.datetime(2020,1,1,12,0,0)})
worksheet = workbook.add_worksheet('My Report')
worksheet.write(0,0,'My new report')
worksheet.write(2,0,'Name')
worksheet.write(2,1,'Age')
worksheet.write(2,2,'Points.')
worksheet.write(3,0,'Alpha')
worksheet.write(3,1,30)
worksheet.write(3,2,100)
worksheet.write(4,0,'Bravo')
worksheet.write(4,1,31)
worksheet.write(4,2,98)
worksheet.write(5,0,'Charlie')
worksheet.write(5,1,32)
worksheet.write(5,2,102)
worksheet.autofilter(2,0,5,2)
worksheet = workbook.add_worksheet()
worksheet = workbook.add_worksheet()
worksheet = workbook.add_worksheet()
worksheet = workbook.add_worksheet()
worksheet.write(0,0,'My other report')
worksheet.write(2,0,'Name')
worksheet.write(2,1,'Age')
worksheet.write(2,2,'Points.')
worksheet.write(3,0,'Alpha')
worksheet.write(3,1,30)
worksheet.write(3,2,100)
worksheet.write(4,0,'Bravo')
worksheet.write(4,1,31)
worksheet.write(4,2,98)
worksheet.write(5,0,'Charlie')
worksheet.write(5,1,32)
worksheet.write(5,2,102)
worksheet.autofilter(2,0,5,2)
workbook.close()

# example14
workbook = xlsxwriter.Workbook('examples/example14.xlsx')
workbook.set_properties({'created': datetime.datetime(2020,1,1,12,0,0)})
worksheet = workbook.add_worksheet('My Report')
workbook.close()
